spring:
  cloud:
    config:
      server:
        sweagle:
          scheme: https
          host: testing.sweagle.com
          port: 443
          export-format: json
          token: XXX
          configdataset: spring-config
          parser: spring-demo
